### ISSUE TITLE
Web Resources

### ISSUE THREAD

**Issue by webmozart** [puli/issues#1]
Right now, the user of an application has no control over where the web assets of installed Composer packages are placed. These packages need to assume where their assets are going to be installed and use this path in their templates:

```html
<link href="/vendor/profiler/css/style.css" type="text/css">
```

Here, for example, the "vendor/profiler" package expects me to install its CSS files under exactly this path in my web directory and I have no way to change this.

To solve this problem, I propose to add a `WebResourceInterface` to Puli. The interface is very simple:

```php
interface WebResourceInterface
{
    public function setWebPath($webPath);

    public function getWebPath();
}
```

Instead of hard-coding the path to the CSS file, the profiler package would then do:

```html+php
<link href="<?php echo $repo->get('/vendor/profiler/css/style.css')->getWebPath() ?>" type="text/css">
```

Or in Twig:

```jinja
<link href="{{ asset('/vendor/profiler/css/style.css') }}" type="text/css">
```

Or using relative paths:

```jinja
{# /vendor/profiler/views/index.html.twig #}
<link href="{{ asset('../css/style.css') }}" type="text/css">
```

The application can configure the web path in composer.json:

```json
{
    "name": "my/application",
    "require": {
        "vendor/profiler": "*"
    },
    "extra": {
        "puli-web-paths": {
            "/vendor/profiler/css": "/css/profiler"
        }
    }
}
```

At last, the resources from the "vendor/profiler" package need to be copied to the "/css/profiler" directory. This could be done by the Composer plugin if the "puli-web-dir" setting is present:

```json
{
    "name": "my/application",
    "require": {
        "vendor/profiler": "*"
    },
    "extra": {
        "puli-web-dir": "public_html",
        "puli-web-paths": {
            "/vendor/profiler/css": "/css/profiler"
        }
    }
}
```

If that setting is not there, the application would need decide how to copy the files, for example with Grunt.

Additionally, a "web-symlinks" setting should exist. When set to true, the resources are symlinked to the web directory.

**Comment by jvasseur** [comment]
I'm interested by this feature, so if you want i can try creating an implementation.

**Comment by webmozart** [comment]
Hi :) Thanks for your proposal! In fact, this feature is already almost ready (it will be implemented through the resource discovery). I would however be *very* grateful about testing Puli in general and reporting any errors you can find.

**Comment by mickaelandrieu** [comment]
:+1: too, this will be used in BackBee CMS as a real implementation example

**Comment by rejinka** [comment]
I can not wait to use this feature. Exactly what i need for microsites, awesome!

**Comment by webmozart** [comment]
This is implemented now: https://github.com/puli/web-resource-plugin
