### ISSUE TITLE
Assets in public directory or not?

### ISSUE THREAD

**Issue by mnapoli** [puli/issues#101]
In the documentation you mention putting the assets (CSS, JS, …) in a `public/` directory.

Then your examples involve publishing the `public/` directory in a `public_html/` directory. Do you recommend not exposing the `public` directory directly?

If that's the case, why not? And do you recommend exposing everything (e.g. `index.php`) as a resource/symlink too? Or just assets?

**Comment by webmozart** [comment]
Could it be you are confusing the public directory in a package and the document root of a web server? Each package has its own `public` directory which is copied to the document root (`public_html`, ...).

What can we do to explain this better in the docs?

**Comment by mnapoli** [comment]
Ah OK I see what you mean. Currently I'm having both the use case of a package (so indeed `res/public` is **not** the document root) and of an application (which uses packages). I'm writing (or rather playing with) a module system, so I need to consider the end user POV too (i.e. how they should write their app).

Maybe Puli is mostly meant at helping for packages. I just wanted to use Puli everywhere. Just like in Symfony there is an `AppBundle` (at least per best practices), I am in the same pattern of making the whole application behave like any other package. So I have a `res/` directory and everything inside it is accessible through Puli using the `/app/` Puli path.

I think my use case is consistency (as I said on Twitter), so that writing a bundle/package is very similar to writing an application.

So I guess my question can be reworded as: should assets **of an application** be in `res/public` and symlinked to `public` (the document root of the web server), or should they be put straight in the public directory? Or rather, do you see any reason to prefer one or the other?

Maybe there are advantages with deployment, abstracting all paths the same way, allowing the app to override stuff in packages, etc? But maybe it's just a matter or preferences and for me to decide? :p

**Comment by webmozart** [comment]
Your app's assets should be put to `res/public` and mapped to the docroot of the server with `$ puli publish`. So yes, your app's assets are just like any other package's assets.

The steps are:

1. Put your app's assets into `res/public`
2. Publish your app's public directory to the server (`puli publish /app/public localhost`)
3. Publish your packages' public directories to the server (`puli publish /vendor/foo/public localhost /foo`)
4. Install the packages

Step 4 is currently done with `puli publish --install` and creates symlinks in the document root. In the future, this will be handled by plugins for Gulp, Grunt etc. (see #88, #97).

**Comment by mnapoli** [comment]
OK awesome that's exactly the answer I was looking for :) Thank you!

Just a quick feedback while I got your attention :) Puli is incredibly awesome. Only problems I see for now:

- to set it up means understanding it completely, which honestly is hard (the docs are very complete, I have no idea/advice on how to improve that yet but will suggest anything I can think of to help)
- to see the full benefits and switch to it, it needs to be set up/work out of the box e.g. in a framework

I'm currently playing with the second thing. I'm going through learning how to use it correctly. But from a user's POV, once it's all set up, it's awesome. It's a bit like Composer I think. It was hard to see the benefits at first, at switching to it took effort. But now the benefits are obvious.

So keep on! :)

**Comment by webmozart** [comment]
Thanks for the feedback :) I agree with your points. The ultimate goal is to have it set up out of the box in most major projects/frameworks so that the end user primarily needs to care about Puli's usage, not so much about how it works.
