### ISSUE TITLE
Implement LinkResource

### ISSUE THREAD

**Issue by webmozart** [puli/issues#107]
A new resource type LinkResource should be supported by all repositories. The idea is something like this:

```php
$repo->add('/app', new DirectoryResource(...));
$repo->add('/acme/blog', new DirectoryResource(...));

// Use application layout in the blog
$repo->add('/acme/blog/views/layout.html.twig', new LinkResource('/app/views/layout.html.twig');
```

The difference to using a FileResource is that with LinkResource, relative paths would remain functional. For example, if we do:

```php
$repo->add('/acme/blog/views/layout.html.twig', new FileResource('/path/to/app/layout.html.twig'));
```

then a relative path in the file would be resolved relative to `/acme/blog/views/layout.html.twig`, and not `/app/views/layout.html.twig`, as expected. With LinkResource, this is fixed.

The class should support a method `getTarget()` that returns the target resource (fetched from the attached repository) and a method `getTargetPath()` that returns the path of the target resource.

**Comment by tgalopin** [comment]
What's the milestone of this?

**Comment by webmozart** [comment]
Updated. This needs to be in 1.0.

**Comment by webmozart** [comment]
Without this feature, resource overriding is a bit useless.

**Comment by tgalopin** [comment]
I think I'm missing something with this feature. Can you describe how it would work a bit more (on Gitter if you want) ? I don't get what you want to do with this.

**Comment by webmozart** [comment]
Technically, LinkResource really just stores the path of another resource. It's a reference to that resource, like links on the filesystem.

Imagine the following Twig template:

```
<img src="{{ resource_url('../images/logo.png') }}" />
```

Let's add this template to a repository:

```php
$repo->add('/app/views/layout.html.twig', new FilesystemResource('...'));
```

This template will look for `/app/images/logo.png`, which is fine.

Now imagine we want to use this template to override another template, like `/blog/views/layout.html.twig`. At the moment, we would do:

```php
$repo->add('/blog/views/layout.html.twig', new FilesystemResource(...));
```

Now `/blog/views/layout.html.twig` is properly replaced by our own template, but all relative paths therein fail. The image `/blog/images/logo.png`, of course, doesn't exist.

The solution is to only link at the other resource:

```php
$repo->add('/blog/views/layout.html.twig', new LinkResource('/app/views/layout.html.twig'));
```

When resolving relative paths, we can now take the path of the linked resource as base path instead of the path of the link.

Better?

**Comment by tgalopin** [comment]
I think I got it. I'll try to do that. Thanks!
