### ISSUE TITLE
PuliCssUtils in the Assetic extension has many undefined variables

### ISSUE THREAD

**Issue by stof** [puli/issues#108]
See https://scrutinizer-ci.com/g/puli/assetic-extension/issues/master/files/src/Util/PuliCssUtils.php?selectedLabels[0]=9&orderField=path&order=asc

**Comment by tgalopin** [comment]
I think the assetic extension is not maintained anymore, is it @webmozart ?

**Comment by webmozart** [comment]
That's correct.

**Comment by stof** [comment]
I suggest updating the readme of the package to tell it is abandonned (the repo description says it, but it is less visible)

**Comment by webmozart** [comment]
@stof done, good suggestion!
