### ISSUE TITLE
All packages should be tested against their lowest dependencies on Travis

### ISSUE THREAD

**Issue by stof** [puli/issues#110]
This will allow finding issues with lower constraint bounds

**Comment by tgalopin** [comment]
I completely agree with this.

I did it for the puli/repository and it showed that there is a problem with the current dependencies: https://github.com/puli/repository/pull/42.

**Comment by tgalopin** [comment]
Given the amount of errors detected, I think it's a great idea :) .

**Comment by webmozart** [comment]
Woa you guys rock :)

**Comment by stof** [comment]
@tgalopin I made some comments in the twig-extension PR. Please take them into account for all packages

**Comment by tgalopin** [comment]
I'll, thanks!

**Comment by webmozart** [comment]
This is fixed now. :)
