### ISSUE TITLE
Fix tests on Windows

### ISSUE THREAD

**Issue by tgalopin** [puli/issues#112]
I ran the tests of all Puli packages under Windows (8.1) to find the issues.

I wrote a PHP script to install all the packages and another one to update them. You can
use them to test in your context easily: https://gist.github.com/tgalopin/7c73922bc060b0685900.

Here are the results:

| Package                   | Status |
|---------------------------|--------|
| [puli/cli](https://github.com/puli/cli) | [![Build status](https://ci.appveyor.com/api/projects/status/n06gckamgc2lr8vl/branch/master?svg=true)](https://ci.appveyor.com/project/webmozart/cli/branch/master) |
| [puli/composer-plugin](https://github.com/puli/composer-plugin) | [![Build status](https://ci.appveyor.com/api/projects/status/ahk24l3m2tahc9ih/branch/master?svg=true)](https://ci.appveyor.com/project/webmozart/composer-plugin/branch/master) |
| [puli/discovery](https://github.com/puli/discovery)| [![Build status](https://ci.appveyor.com/api/projects/status/wmg14bydks4xwqs2/branch/master?svg=true)](https://ci.appveyor.com/project/webmozart/discovery/branch/master) |
| [puli/manager](https://github.com/puli/manager) | [![Build status](https://ci.appveyor.com/api/projects/status/eb5apotdnp0h021b/branch/master?svg=true)](https://ci.appveyor.com/project/webmozart/manager/branch/master) |
| [puli/repository](https://github.com/puli/repository) | [![Build status](https://ci.appveyor.com/api/projects/status/a0g5jdtj78wv53c0/branch/1.0?svg=true)](https://ci.appveyor.com/project/webmozart/repository/branch/1.0) |
| [puli/symfony-bridge](https://github.com/puli/symfony-bridge) | [![Build status](https://ci.appveyor.com/api/projects/status/3ldji4vsb0e82oqa/branch/master?svg=true)](https://ci.appveyor.com/project/webmozart/symfony-bridge/branch/master) |
| [puli/twig-extension](https://github.com/puli/twig-extension) | [![Build status](https://ci.appveyor.com/api/projects/status/bnnfj371jp7tb9gx/branch/master?svg=true)](https://ci.appveyor.com/project/webmozart/twig-extension/branch/master) |
| [puli/url-generator](https://github.com/puli/url-generator) | [![Build status](https://ci.appveyor.com/api/projects/status/x7qpeo9er78ftxk0/branch/master?svg=true)](https://ci.appveyor.com/project/webmozart/url-generator/branch/master) |
| [webmozart/assert](https://github.com/webmozart/assert) | [![Build status](https://ci.appveyor.com/api/projects/status/lyg83bcsisrr94se/branch/master?svg=true)](https://ci.appveyor.com/project/webmozart/assert/branch/master) |
| [webmozart/console](https://github.com/webmozart/console) | [![Build status](https://ci.appveyor.com/api/projects/status/b62lnbmfkv754sco/branch/master?svg=true)](https://ci.appveyor.com/project/webmozart/console/branch/master) |
| [webmozart/expression](https://github.com/webmozart/expression) | [![Build status](https://ci.appveyor.com/api/projects/status/6dstc380h5pr5rk3/branch/master?svg=true)](https://ci.appveyor.com/project/webmozart/expression/branch/master) |
| [webmozart/glob](https://github.com/webmozart/glob) | [![Build status](https://ci.appveyor.com/api/projects/status/das6j3x0org6219m/branch/master?svg=true)](https://ci.appveyor.com/project/webmozart/glob/branch/master) |
| [webmozart/key-value-store](https://github.com/webmozart/key-value-store) | [![Build status](https://ci.appveyor.com/api/projects/status/own4xo856g5asgc8/branch/master?svg=true)](https://ci.appveyor.com/project/webmozart/key-value-store/branch/master) |
| [webmozart/path-util](https://github.com/webmozart/path-util) | [![Build status](https://ci.appveyor.com/api/projects/status/d5uuypr6p162gpxf/branch/master?svg=true)](https://ci.appveyor.com/project/webmozart/path-util/branch/master) |
| [webmozart/json](https://github.com/webmozart/json) | [![Build status](https://ci.appveyor.com/api/projects/status/icccqc0aq1molo96/branch/master?svg=true)](https://ci.appveyor.com/project/webmozart/json/branch/master) |

This issue will be updated every time we make an improvement and the updates will be listed
here.

Updates
=======

- ~~`puli/repository` now works thanks to https://github.com/puli/repository/pull/46~~ The LinkResource is failing
- `puli/cli` now works thanks to https://github.com/puli/cli/pull/9

**Comment by webmozart** [comment]
Thanks :) Here is an attempt at fixing the CLIi: puli/cli#9

**Comment by temp** [comment]
Additionally, webmozart/json:
Fails, https://gist.github.com/temp/a739c64176615ef880a5

**Comment by stof** [comment]
@webmozart what do you think about using AppVeyor to run tests on Windows ? You can look at the Symfony 2.3 branch for a setup (you can simplify the handling of PHPUnit by just downloading the phar though, as you are not affected by the fact that the phar contains the Yaml component, unlike symfony)

**Comment by webmozart** [comment]
@stof A lot! In fact, I already enabled it for puli/repository. As soon as someone submits a PR with an appveyor.yml this should be working already.

**Comment by stof** [comment]
@webmozart the issue with this is that it will mark all PRs as failing until a config file is added...

**Comment by webmozart** [comment]
@stof no, I disabled AppVeyor for all branches without appveyor.yml

**Comment by stof** [comment]
ah, better than what was done on the Symfony repository...

**Comment by webmozart** [comment]
see #115

**Comment by tgalopin** [comment]
I started working on the Appveyor integration, this issue will be easier to work on once it will be done.

**Comment by webmozart** [comment]
All repositories are tested on AppVeyor now. The failing test results are linked above, feel free to work on fixes everyone. :)

**Comment by tgalopin** [comment]
The last failing tests of repository are fixed in https://github.com/puli/repository/pull/61.

**Comment by webmozart** [comment]
All green \o/
