### ISSUE TITLE
Support Class Discovery

### ISSUE THREAD

**Issue by webmozart** [puli/issues#114]
The Discovery component should be extended to support discovery of PHP classes. This includes various changes:

* The `ResourceDiscovery` interface should be agnostic of resources. A new interface `Binding` should be introduced: `bind($glob, $type)` then becomes `addBinding(Binding $binding)`. `ResourceBinding` will be an implementation/sub-interface of `Binding`. Equally, there'll be a `ClassBinding` for classes.

* Instead of using simple strings for binding types, we'll use interface or class names (FQCNs). The metadata of those FQCNs will be stored in `BindingType` objects, such as the allowed parameters or whether the type works with resources, classes or both. `BindingType` objects can be read from `puli.json` (as right now) or from annotations on the interface/class:

```php
use Puli\Discovery\Api\Annotations\Accept;
use Puli\Discovery\Api\Annotations\BindingType;
use Puli\Discovery\Api\Annotations\Parameter;
use Puli\Discovery\Api\Annotations\Parameters;

/**
 * @BindingType
 * @Accept("RESOURCE")
 * @Parameters({
 *   @Parameter("priority", default=1),
 *   @Parameter("name", index=true),
 * })
 */
interface Service {}
```

Here's a very rough sketch of the interfaces and classes we'll need:

```php
interface Binding extends Serializable
{
    /**
     * @return Uuid
     */
    public function getUuid();

    /**
     * @return BindingType
     */
    public function getType();

    public function getParameterValues();

    public function getParameterValue($parameterName);

    public function hasParameterValue($parameterName);
}

class ResourceBinding implements Binding
{
    public function getResources();

    public function getQuery();

    public function getLanguage();
}

class GlobBinding extends ResourceBinding
{
    public function findResources($glob);
}

class ClassBinding implements Binding
{
    public function getClassName();

    public function createInstance($args...);
}

class BindingType
{
    /**
     * @return string Class name of the type class
     */
    public function getClassName();

    /**
     * @param string Class name of a Binding implementation
     */
    public function acceptsBinding($className);

    /**
     * @return string[] Class names of Binding implementations
     */
    public function getAcceptedBindings();

    /**
     * @return BindingParameter[]
     */
    public function getParameters();

    /**
     * @return BindingParameter
     */
    public function getParameter($name);

    public function hasParameter($name);

    public function getParameterValues();

    public function getParameterValue($name);
}

interface BindingTypeLoader
{
    public function loadBindingType($className);
}

interface ResourceDiscovery
{
    public function findBindings($className, array $parameterValues = array());

    public function hasBindings($className = null, array $parameterValues = array());

    public function getBindings();

    public function isTypeDefined($className);

    public function getBindingType($className);

    public function hasBindingTypes();

    public function getBindingTypes();
}

interface EditableDiscovery
{
    public function addBinding(Binding $binding);

    public function removeBinding(Uuid $uuid);

    public function clearBindings();

    public function defineType(BindingType $type);

    public function undefineType($className);

    public function clear();
}
```

**Comment by stof** [comment]
should instantiating an object really be the responsibility of the ClassBinding ? this looks weird to me

**Comment by webmozart** [comment]
@stof This would be just a convenience mechanism, like `getResources()` on ResourceBinding. The 90% use case for me is to bind classes with no-arg constructors to bootstrap the application, like Symfony's Bundle classes.

**Comment by tmaroschik** [comment]
Two notes on that: 
* instead of custom annotation tags, maybe use namespaced doctrine/annotions style annotations. those collide less with different frameworks
* did you consider implementing `\ArrayAccess` and `\Iterator` for the different interfaces? Because those feel to me much like typed collections, and collections are accessed very easily by those built in interfaces

**Comment by webmozart** [comment]
@tmaroschik Of course we should use namespaced Doctrine annotations. I just left out the use statements for simplicity.

In the above example, non of the classes semantically is a collection (we have services and domain objects), so I don't think those interfaces make sense here.

**Comment by tmaroschik** [comment]
@webmozart ok. It just looked to me like a "bag" for parameters or binding types

Further, consider the performance impact of loading & parsing more distinct classes/interfaces. During my research upon improving the performance of TYPO3 one of the results was that you cannot optimize class loading any further, and the only way to speed things up is to reduce IO. Class Loading is also IO, even when loaded from Opcache. We had once a package class per package, that contained just some basic information. In the end we had to drop this idea, because a TYPO3 site can easily consist of 60+ packages and took a different approach.

**Comment by webmozart** [comment]
@tmaroschik Thanks for the input! In production, the Discovery mechanism would ideally not be run at all, or if necessary then with an optimized ResourceDiscovery object that requires a minimum amount of code and classes. We take a similar approach with the Repository component.

**Comment by webmozart** [comment]
The other Puli repositories still need to be fixed to work with the new API. That's probably:

* UrlGenerator
* Manager
* CLI
