### ISSUE TITLE
Resource will be a reserved keyword

### ISSUE THREAD

**Issue by EmanueleMinotto** [puli/issues#119]
Quoting Style CI:
> In php 7, "resource" is a reserved name and you can't use it for a class

Ref: https://twitter.com/TeamStyleCI/status/645906122524753920 & https://wiki.php.net/rfc/reserve_even_more_types_in_php_7

This could be a problem for `Puli\Repository\Api\Resource\Resource`, should it be renamed?

**Comment by tgalopin** [comment]
It does not seem to be a problem: https://travis-ci.org/puli/repository/jobs/80213636. Is it something not yet present in the PHP7 nightly of Travis?

**Comment by EmanueleMinotto** [comment]
I didn't investigate yet. Could it be a big BC?
Anyway this problem could be ignored until the release of puli (imo).

**Comment by tgalopin** [comment]
It is definitely a problem for StyleCI, but we can disable the phpdoc_types fixer to ignore it. Would it be fine for you @webmozart ?

**Comment by webmozart** [comment]
Yes, let's do that for now.

**Comment by stof** [comment]
``resource`` does not trigger an error in PHP 7, but they document that it should be considered reserved for future use: http://php.net/manual/en/migration70.incompatible.php#migration70.incompatible.other.classes
This is why StyleCI is complaining.

Given that renaming it in Puli is a BC break, it would be better to do it before reaching 1.0 instead of facing the need for a BC break later on if PHP actually makes use of it as a reserved keyword.

**Comment by webmozart** [comment]
Any suggestion for a good name? `PuliResource`?

**Comment by EmanueleMinotto** [comment]
`PuliResource` :+1:

**Comment by stof** [comment]
@webmozart I can't think of a better suggestion

**Comment by webmozart** [comment]
Well we still have `PResource`, `Resorz` or `Resource_` :sunglasses:

**Comment by webmozart** [comment]
On a serious side, let's go for `PuliResource`. Anybody wants to work on that? (@EmanueleMinotto?) We also need to enable the phpdoc_types check again.

**Comment by EmanueleMinotto** [comment]
@webmozart sure, I can do it :+1:

**Comment by webmozart** [comment]
This fix needs to be applied to all repositories:

- [ ] [puli/repository](/puli/repository)
- [ ] [puli/discovery](/puli/discovery)
- [ ] [puli/url-generator](/puli/url-generator)
- [ ] [puli/manager](/puli/manager)
- [ ] [puli/cli](/puli/cli)
- [ ] [puli/composer-plugin](/puli/composer-plugin)
- [ ] [puli/twig-extension](/puli/twig-extension)
- [ ] [puli/symfony-bridge](/puli/symfony-bridge)
- [ ] [puli/symfony-bundle](/puli/symfony-bundle)

**Comment by webmozart** [comment]
@EmanueleMinotto Will you have time to fix the other repositories soon? Currently, most repositories are broken on master.

**Comment by webmozart** [comment]
This is finished now. :)
