### ISSUE TITLE
Upgrade to ramsey/uuid 3.0

### ISSUE THREAD

**Issue by webmozart** [puli/issues#122]
All packages that use ramsey/uuid should be upgraded to version 3.0. The upgrade should be simple - the main change was in the namespace of the classes in the package which changed from Rhuumsa to Ramsey.

**Comment by BenoitLeveque** [comment]
i think, i can do it

**Comment by webmozart** [comment]
@BenoitLeveque That would be awesome! :) The best is if you search the composer.json files in all [github.com/puli](/puli) repositories for those that reference that package.

**Comment by BenoitLeveque** [comment]
@webmozart ramsey/uuid require php 5.4, but we still use php 5.3 inside the .travis.yml file.

it's ok to remove php 5.3 from the travis build?

**Comment by webmozart** [comment]
No, we need to support 5.3. Damn. Closing then.
