### ISSUE TITLE
Remove unused files on dist

### ISSUE THREAD

**Issue by EmanueleMinotto** [puli/issues#124]
Considering CI systems, I think some files (including the `tests` directory) should be removed when developers download puli dependencies using `--prefer-dist`.

thephpleague is doing this: https://github.com/thephpleague/skeleton/blob/master/.gitattributes

If it's ok I can send PRs removing puli dev dependencies in the `.gitattributes` for each repo.

**Comment by webmozart** [comment]
Great suggestion :) Go ahead!

**Comment by EmanueleMinotto** [comment]
Uhm... actually none of them pass tests, I'll investigate on the problems.

**Comment by webmozart** [comment]
Can you open a PR on the twig-bridge as well?

**Comment by webmozart** [comment]
This is fixed now! :)

**Comment by EmanueleMinotto** [comment]
Yeah! :+1:
