### ISSUE TITLE
Links should be handled properly when adding/removing resources

### ISSUE THREAD

**Issue by webmozart** [puli/issues#129]
When adding resources to or removing them from a repository, linked directories should be handled properly. Some cases that come to mind:

* When adding `/link/file` where `/link` => `/target`, the file should be added at `/target/file`
* When adding `/link1/file` where `/link1` => `/link2` and `/link2` => `/target`, the file should be added at `/target/file`
* Same for files in sub-directories of a link, e.g. `/link/dir/file`
* Same for removal
* When replacing a directory with a link, the contents of that directory must be removed first. E.g. when adding a `LinkResource` to `/dir` where `/dir/file` existed before, that file must not exist anymore after adding the link (unless of course `/target/file` exists)

Maybe there are some more cases that need to be tested.

**Comment by msojda** [comment]
Hi there! :)

I've already started working on it - if I have any questions, I'll ask here. Please be tolerant - it will be my first contribution. :)

**Comment by EmanueleMinotto** [comment]
@msojda don't forget to join on gitter ;)

[![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/puli/issues?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

**Comment by webmozart** [comment]
@msojda Yes, you should definitely join Gitter! Also, talk to @tgalopin as I think that he has started to work on this.

**Comment by tgalopin** [comment]
@msojda I did start to work on this but I didn't do much so don't hesitate to try :) . If you need help, I can probably give a hand :) .

**Comment by tgalopin** [comment]
We discussed this a bit with @webmozart and we concluded that for the moment, this feature needs too much work for probably not a big use case. We will see in the future if this is needed, but for the moment it's just too complicated. I let you close this @webmozart?
