### ISSUE TITLE
"puli self-update" should download from puli.io

### ISSUE THREAD

**Issue by webmozart** [puli/issues#136]
The "puli self-update" command should be changed to download the PHAR from puli.io instead of GitHub. This should fix the command on PHP < 5.6.

See puli/installer#2 for details.

**Comment by EmanueleMinotto** [comment]
Reading https://github.com/padraic/phar-updater#sha-1-hash-synchronisation I see some differences between the two systems:

* to continue with the `padraic/phar-updater` package switching from the github strategy to the sha1 strategy, some changes should be done to https://github.com/puli/puli.io/tree/master/source/download too
* currently there is a stability option, with the sha system this option will be removed
* with the sha strategy there will be only *new* and *old* version, while keeping the github strategy more versions would be available

Can I proceed with a PR to puli/puli.io and another PR to puli/cli switching from the github strategy to the sha strategy?

**Comment by webmozart** [comment]
@EmanueleMinotto I think the best option would actually be to implement a custom strategy. That shouldn't be too hard to do. What do you think?

**Comment by EmanueleMinotto** [comment]
It depends, what's the custom strategy?

Imo the Github strategy should be considered again before implementing an alternative strategy:

1. it's already integrated with the puli/cli repo, there's no need to update puli/puli.io too on each release (or commit if the unstable option should still be available, but I think it won't be available outside of the github strategy)
2. allows more versions than the sha strategy
3. the release asset can be built and uploaded [automatically](https://developer.github.com/v3/repos/releases/#upload-a-release-asset) using travis

**Comment by webmozart** [comment]
@EmanueleMinotto The reason why we can't work with the GitHub strategy is that it doesn't work on PHP < 5.6. Those versions can't handle the SSL certificates that GitHub uses, that's why we need to download from a custom location with SSL certificates that work on PHP < 5.6.

For the custom strategy, see https://github.com/puli/installer/pull/2/files. The available versions are listed in https://puli.io/download/versions.json. Every version has a matching download in `https://puli.io/download/<version>/puli.phar`. It's pretty simple, really.

**Comment by EmanueleMinotto** [comment]
ok, than I'll implement a custom strategy based on those files :)

**Comment by webmozart** [comment]
Thanks! :) Everything else you said is of course completely valid, and can be implemented with the custom strategy as well as far as I see.
