### ISSUE TITLE
Use the last version of Composer on TravisCI

### ISSUE THREAD

**Issue by EmanueleMinotto** [puli/issues#139]
Travis is using an old version of Composer and if not required in the `.travis.yml` file it could generate errors like this: https://travis-ci.org/puli/silex-provider/jobs/86696687#L366

So I think the install part should be replaced by:
``` yaml
install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer update $COMPOSER_FLAGS --prefer-source -n
```

**Comment by tgalopin** [comment]
It was something we avoided to not add useless test time. Perhaps would it be better to add it only in failing repositories.

**Comment by EmanueleMinotto** [comment]
@tgalopin that sounds good too to me, so should I add it only to puli/composer-plugin, puli/symfony-bundle and puli/silex-provider?

**Comment by tgalopin** [comment]
I think it's a good idea. What do you think @webmozart ?

**Comment by webmozart** [comment]
Sounds like a plan! :) But why on the composer-plugin and symfony-bundle repos? Those are green, no?

**Comment by EmanueleMinotto** [comment]
symfony-bundle has the composer-plugin as a dependency and the composer-plugin is related to the problem reported above.

Honestly I don't know why symfony-bundle passes tests and the silex-provider doesn't, both of them are using the same outdated version of Composer.

Probably Murphy's law affects only me hahaha

**Comment by webmozart** [comment]
Ok then. So we can close all other PRs?

**Comment by EmanueleMinotto** [comment]
@webmozart yes thanks :)
