### ISSUE TITLE
PHP 7 support

### ISSUE THREAD

**Issue by EmanueleMinotto** [puli/issues#145]
PHP 7 was released few days ago, what about its addition to the `.travis.yml` matrix of PHP versions?

**Comment by tgalopin** [comment]
I agree. At the beginning we should put it in `allow_failures` though to avoid problems, but in the future we should support it.

**Comment by EmanueleMinotto** [comment]
@tgalopin I've added it but I don't know why it's not created the instance using PHP 7 :\
anyway my changes are based on https://docs.travis-ci.com/user/languages/php/#PHP-7

**Comment by tgalopin** [comment]
Awesome, thanks!

I think the nightly is the problem: if you remove  it, it should use the 7 stable.

**Comment by EmanueleMinotto** [comment]
Solved, the problem was that I didn't include the version `7.0` in the `matrix.include` list, now should be ok.

**Comment by tgalopin** [comment]
Great! I think you could remove the allowed failures for the repositories in which PHP7 works once the builds will be done.

What do you think of this @webmozart?

**Comment by webmozart** [comment]
Hi :) Thanks for this! I think you should remove allowed failures for PHP7 everywhere. If a repository fails on PHP7, we need to fix this ASAP.

**Comment by EmanueleMinotto** [comment]
@webmozart done :)

**Comment by webmozart** [comment]
Thanks @EmanueleMinotto, all merged! :)
