### ISSUE TITLE
Question: way to trigger a specific function when bindings are updated

### ISSUE THREAD

**Issue by moufmouf** [puli/issues#146]
Hi @webmozart !

I have a specific need regarding Puli. Basically, I would like to trigger some specific code each time a binding is updated. So far, bindings can be updated when a user runs a `composer update` (through the Composer plugin), or through the CLI.

What I would like to do is trigger a specific action at this time (if you remember our discussion at the Paris ForumPHP, I'm trying to trigger the compilation of a container and my binding is containing a list of service definition providers).

I think the way to go is to write a Puli plugin, but I have no idea on the classes / methods I should use to trigger some code at some point. Is there any kind of event system I can tap into? Would you do it this way or am I thinking the wrong way?

**Comment by webmozart** [comment]
Hi @moufmouf! Yes, the way to go is with a plugin. The activation of plugins will be simplified with #144. Also, we need to add the events you need. Right now, not many events have been added to Puli's core yet. You can check the currently available events in https://github.com/puli/manager/blob/master/src/Api/Event/PuliEvents.php.

**Comment by moufmouf** [comment]
@webmozart Thanks for the quick answer!

Looking at the `PuliEvents.php` file, I saw there is a `PuliEvents::GENERATE_FACTORY` event.
It seems fired in the `FactoryManagerImpl::generateFactoryClass` method, which is triggered from the `refereshFactoryClass` method. See: https://github.com/puli/manager/blob/master/src/Factory/FactoryManagerImpl.php#L235-L237

Since the factory seems refreshed each time the configuration changes, I guess I could listen to this event to listen for changes in the bindings. Am I correct? If so, we can close this issue!

**Comment by webmozart** [comment]
I can't guarantee that this event will always be triggered when bindings are updated, but for the forseeable future that should remain true. :)
