### ISSUE TITLE
Classloader issues when working with plugins

### ISSUE THREAD

**Issue by moufmouf** [puli/issues#147]
I'm not completely sure if I'm doing things right (since Puli Plugins are quite new), but here we go.

I created a class extending `PuliPlugin` in my package.

I ran:

```php
puli plugin -i TheCodingMachine\\Yaco\\Discovery\\YacoPlugin
```

Result: The plugin class TheCodingMachine\Yaco\Discovery\YacoPlugin does not exist.
Important note: puli is installed globally.

Now, I run:

```php
vendor/bin/puli plugin -i TheCodingMachine\\Yaco\\Discovery\\YacoPlugin
```

**success!** It seems that the global puli install is unable to detect my plugin class. This is at the same time normal, but also a real problem for plugin developers.

Also, if I install the "puli/composer-plugin" package, each time a `composer dumpautoload` is triggered, I get an error regarding the plugin that is not found:

```
Generating autoload files
Warning: Could not load Puli configuration: 

                                                                               
  [Puli\Manager\Api\InvalidConfigException]                                    
  The plugin class TheCodingMachine\Yaco\Discovery\YacoPlugin does not exist.  
                                                                               


Exception trace:
  ()
    phar:///usr/local/bin/puli/vendor/puli/manager/src/Api/Puli.php:971
  Puli\Manager\Api\Puli->validatePluginClass()
    phar:///usr/local/bin/puli/vendor/puli/manager/src/Api/Puli.php:845
  Puli\Manager\Api\Puli->activatePlugins()
    phar:///usr/local/bin/puli/vendor/puli/manager/src/Api/Puli.php:331
  Puli\Manager\Api\Puli->start()
    phar:///usr/local/bin/puli/src/PuliApplicationConfig.php:74
  Puli\Cli\PuliApplicationConfig->__construct()
    phar:///usr/local/bin/puli/bin/puli:21
  {closure}()
    phar:///usr/local/bin/puli/vendor/webmozart/console/src/ConsoleApplication.php:96
  Webmozart\Console\ConsoleApplication->__construct()
    phar:///usr/local/bin/puli/bin/puli:21
  require()
    /usr/local/bin/puli:10
```

Once more, this seems logical (the Composer plugin does not have access to the composer autoloader that it just generated), but it is a problem for plugin usage.

Am I doing something wrong or is it something that needs fixing in Puli's code base (maybe requiring `vendor/autoload.php` if plugins are used?)

**Comment by webmozart** [comment]
Thanks for reporting this issue @moufmouf! In general, this *should* work like this:

* When you use the Composer plugin, your project's `autoload.php` is registered as Puli's "bootstrap-file". Henceforth, Puli is able to load all classes of your project.

* After doing this, installing and using Puli plugins shouldn't pose any problems.

I suppose that you added your plugin before requiring the Composer plugin. Is that right?

**Comment by moufmouf** [comment]
:+1: That's exactly what happened. To fix this, I deleted my `puli.json` file, ran `composer update` (with the composer plugin declared in composer.json). Then, I installed my plugin again (`puli plugin -i XXX`) and everything works fine now.

Thanks!

**Comment by webmozart** [comment]
Cool, thanks for the update. :)
