### ISSUE TITLE
[Help] Customizing a 3rd party library

### ISSUE THREAD

**Issue by harikt** [puli/issues#150]
Hi,

First thanks for your good work.

Have a question for it seems there was a strange issue on testing it. ( Not saying it is a bug for I may have done something wrong ) 

Installed a 3rd party library. Everything was working fine.

I started to customize some of the css, js file.
So mapped the `harikt/contact` to `res` of the current application.

Add a different css, it worked fine. But the js was not added. But it looks like the js is not found when clicking on the js link. The application is served by php server and not via apache.

Tree

```
├── app
│   ├── public
│   │   ├── css
│   │   │   └── main.css
│   │   ├── images
│   │   └── js
│   └── views
└── harikt
    └── contact
        ├── public
        │   ├── css
        │   │   └── main.css
        │   ├── images
        │   └── js
        │       └── app.js
        └── views
            └── contact.php
```

All source code of the application are over https://github.com/harikt/puli-demo-application .

Thank you

**Comment by harikt** [comment]
I did tried adding a `app.js` on the `/res/public/js/` of the root and it works! . If there is no js it cannot locate.

**Comment by harikt** [comment]
Same applies when there is only `app.js` and no `main.css` file.

**Comment by webmozart** [comment]
Did you resolve this problem? I just downloaded your application. I cannot even open `/contact`, since there seems to be an error 500. Should this work?

**Comment by harikt** [comment]
no. I couldn't resolve the issue. Did you ran composer install ?

**Comment by harikt** [comment]
So I think I know why you got 500. Do this for I removed the puli.json from application for this is for a tutorial and need to write step by step things ;) .

```php
puli server -a localhost www
puli publish /harikt/contact/public localhost
puli publish --install
```

**Comment by harikt** [comment]
Related #133

**Comment by harikt** [comment]
Thank you @webmozart .
