### ISSUE TITLE
Add the prefer-source option to CI systems

### ISSUE THREAD

**Issue by EmanueleMinotto** [puli/issues#154]
Without the explicit option Composer try to download the dependencies using the dist ([ref](https://getcomposer.org/doc/03-cli.md#install)), but after a number of requests [this problem comes out](https://ci.appveyor.com/project/webmozart/silex-provider/build/1.0.34/job/ngd0tv6s0nltefd1#L256), so every repository should use the `--prefer-source` in CI systems.

Currently missing:

 - [ ] puli/silex-provider (fixed with: https://github.com/puli/silex-provider/pull/6)
 - [ ] puli/gulp-plugin
 - [ ] puli/symfony-bridge
 - [ ] puli/symfony-bundle
 - [ ] puli/twig-extension

**Comment by xabbuh** [comment]
I wouldn't do that on Travis as you wouldn't then be able to cache downloaded packages (using the cache significantly speeds up builds). Isn't AppVeyor able to do some caching too?

**Comment by EmanueleMinotto** [comment]
Yes, Appveyor has a cache too, but it's much more limited than on TravisCI because [resulting archive should not exceed 100 MB](http://www.appveyor.com/docs/build-cache).

**Comment by tgalopin** [comment]
As @xabbuh I think we definitely should keep the TravisCI cache. Also we already have to wait at least 20 minutes for Appveyor so 3 additionnal minutes sometimes seems better than 1 minute every time.

**Comment by webmozart** [comment]
I think the main question is not whether or not to use the Travis CI cache, but about AppVeyor. @EmanueleMinotto started adding --prefer-source do the AppVeyor builds. Does anybody foresee problems with that?

**Comment by Nicofuma** [comment]
You can also use a valid public and permission less token (like nikos is doing here: https://github.com/symfony/symfony/pull/17171)

**Comment by EmanueleMinotto** [comment]
Without the `--prefer-source` also the `.gitattributes` files must be removed, because some repositories have also development dependencies, for example: puli/cli (in some tests) requires some files from puli/repository `tests/` directory, if downloaded via the distribution, those files won't be available.

If the argument moves to have or not have the .gitattributes in puli/* (and than allow the dist version of testing dependencies too), read this: https://www.reddit.com/r/PHP/comments/2jzp6k/i_dont_need_your_tests_in_my_production

**Comment by webmozart** [comment]
@EmanueleMinotto We can fix that by not cross-requiring files from other test directories. It's convenient to do right now, but it's not a must have.

**Comment by webmozart** [comment]
To follow up, I'd rather see us add --prefer-dist everywhere (Travis CI and AppVeyor) to speed up builds.

**Comment by webmozart** [comment]
see https://github.com/puli/issues/issues/169
