### ISSUE TITLE
Add persistent ChangeStream

### ISSUE THREAD

**Issue by webmozart** [puli/issues#155]
As a follow-up of https://github.com/puli/issues/issues/90 and https://github.com/puli/repository/pull/58, we should add a persistent implementation of ChangeStream so that we can actually access the resource versions of a repository loaded from disk.

As @tgalopin mentioned, using a KeyValueStore as backend of the ChangeStream is probably a good idea. The most important property of the ChangeStream is fast reading of versions of a particular resource. Using the resource paths as keys and storing a list of serialized objects in those keys seems like a good solution.

An alternative solution is to use a file format that is optimized for append-only writing and sequential reading. Such a file format would support faster writing, but slower reading. Since read performance is more important for us than write performance, key-value stores seem superior however.

**Comment by webmozart** [comment]
With regard to the second file format, we could implement a SerializingChangeStream that simply serializes/unserializes the complete object array and dumps it to/reads it from a file and compare that with the KeyValueStoreChangeStream.

**Comment by tgalopin** [comment]
The problem we had with store is that they don't necessarily keep order. I agree with the SerializingChangeStream, I would also create a JsonChangeStream.

**Comment by webmozart** [comment]
Why not? If we store arrays in the individual KVS buckets, their contents should remain in order. We don't need versioning across different buckets.
