### ISSUE TITLE
Composer plugin installs when it shouldn't

### ISSUE THREAD

**Issue by gossi** [puli/issues#156]
I'm using puli for my framework, which does a great job so far. Yet I run into an odd situation, where I think puli is running install where it shouldn't. To understand this, here are the two types of packages that explain the requirements of my framework:

```json
{
	"name" : "framework/core",
	"require" : {
		"puli/composer-plugin" : "^1.0@beta"
	}
}
```

```json
{
	"name" : "framework/module",
	"require-dev" : {
		"framework/core" : "dev-master",
		"puli/composer-plugin" : "@beta",
		"puli/repository" : "^1.0@beta"
	}
}
```

So, whenever I run  `composer update` in my module's package, the puli install is run as well - is that supposed to be? I'm asking because it is not a first-class puli-composer-plugin it only has a transitive dependency?

Second are these message while puli is installing:

```
...
Installing webmozart/assert (vendor/webmozart/assert)
Warning: Could not install package "webmozart/assert" (at ./vendor/webmozart/assert): CannotParseArgsException: The "--add" option does not exist.
Installing webmozart/path-util (vendor/webmozart/path-util)
Warning: Could not install package "webmozart/path-util" (at ./vendor/webmozart/path-util): CannotParseArgsException: The "--add" option does not exist.
Installing puli/composer-plugin (vendor/puli/composer-plugin)
Warning: Could not install package "puli/composer-plugin" (at ./vendor/puli/composer-plugin): CannotParseArgsException: The "--add" option does not exist.
...
```
The installation works fine in the core package.

Thanks for clarification.

**Comment by gossi** [comment]
Update, I installed `puli/repository` in core as well and that made the same warnings to show up there, too. So must be something related to `puli/repository`.

**Comment by webmozart** [comment]
Hi @gossi, thank you for reporting your issue! :)

It seems that the version of puli/composer-plugin and of the `puli` CLI that you have installed are not compatible. I suspect that you are using the latest version of puli/composer-plugin, but an older version of the `puli` CLI. You can find which version you have with `puli -V`. You should have version 1.0.0-beta9.

If you don't, update to the latest version by:

* running `puli self-update`, or if that does not work
* running `curl https://puli.io/installer | php` and replacing your `puli` executable by the downloaded PHAR

I created a ticket to detect this problem more easily in the future: #161

**Comment by gossi** [comment]
Hi @webmozart,

I updated my puli-cli executable to be the most recent version (1.0.0-beta9 as we speak), so I thought, if I run `composer update` again, this should run without any warnings, yet it doesn't (same as above) - I also run it a second time, just to be sure, the recent update is still mixing up with a probably older version... also the second time shows the same warnings as above.

Meanwhile, this is my relevant `composer.json` for `framework/core`:

```json
{
	"name" : "framework/core",
	"require" : {
		"php" : ">=5.5",
		"puli/composer-plugin" : "^1.0@beta",
		"puli/repository" : "^1.0@beta",
		"puli/twig-extension" : "^1.0@beta",
		"puli/url-generator": "^1.0@beta",
		"puli/discovery": "@beta"
	}
}
```

Let me know, if I can help with this.

**Comment by gossi** [comment]
Apart from that, the original idea of my issue was untouched yet. With this one here:

`framework/core` => `puli/composer-plugin`
`framework/module` => `puli/repository`

So, the module is a `puli/composer-plugin` because of it's dependency to core, a transitive depency, not a direct dependency. In the case of my module (non-direct composer-plugin dependency) I would not expect puli to run its install routine after a composer update - Any comments on this?

**Comment by webmozart** [comment]
Would you like to join https://gitter.im/puli/issues? It's easier to discuss such details there.

**Comment by webmozart** [comment]
I added a new ticket for this problem: #167
