### ISSUE TITLE
Show help message when bind/type yields empty list

### ISSUE THREAD

**Issue by mnapoli** [puli/issues#157]
When no mapping, bindings or types are defined a call to `puli bind` or `puli type` yields an empty output.

On the contrary, `puli map` yields a very helpful message:

> No path mappings. Use "puli map <path> <file>" to map a Puli path to a file or directory.

It would be great to have a similar message for `bind` and `type` (and maybe other commands I haven't used yet). Personally my experience with both of these commands was very frustrating partially because of that.

**Comment by webmozart** [comment]
:+1:
