### ISSUE TITLE
Puli type: The "-u" option does not exist

### ISSUE THREAD

**Issue by mnapoli** [puli/issues#159]
From http://docs.puli.io/en/latest/discovery/consuming-resources.html

> Binding types can be changed with the type -u (or --update) command. The command takes the name of the binding type as argument and one or more options for the value that you want to change:

>     $ php puli.phar type -u thor/translations \
        --description "A Yaml file with translations for the Translator class."

When I use the `-u` option I get the following result with Puli 1.0.0-beta9:

```bash
$ puli type -u php-di/configuration --description "PHP-DI configuration file"
fatal: The "-u" option does not exist.
```

However `--update` works.

**Comment by webmozart** [comment]
Fixed in puli/cli#31.
