### ISSUE TITLE
Tweak CI configuration

### ISSUE THREAD

**Issue by webmozart** [puli/issues#169]
The CI configuration for Travis and AppVeyor should be improved to speed up our builds. They are quite horribly slow at the moment.

I already did this for puli/discovery and puli/manager with huge improvements. For a template see https://github.com/puli/manager/pull/44.

This should be done for all puli/* and webmozart/* repositories.

**Comment by EmanueleMinotto** [comment]
I have a couple of questions about the template:

* why xdebug should be removed? phpunit can't generate the code coverage without it (visible [here](https://travis-ci.org/puli/manager/jobs/100401973#L242))
* why the `$TRAVIS_REPO_SLUG` env is checked? doesn't work in forks (and I'm not sure for PRs)

**Comment by xabbuh** [comment]
Xdebug is indeed needed to generate code coverage reports. However, it's not necessary to generate them in every single job (see puli/manager#45 for a suggestion on how to generate coverage reports in only one job).

**Comment by webmozart** [comment]
The `$TRAVIS_REPO_SLUG` is checked precisely to prevent forks from using my personal API token :) The token is limited to 5000 requests per hour, hence I'd like to use it for my own repositories only.

Here's a PR for puli/repository that includes the coverage generation as well: https://github.com/puli/repository/pull/83

**Comment by xabbuh** [comment]
@webmozart Do you have separate tokens for the `webmozart` and `puli` packages?

**Comment by webmozart** [comment]
@xabbuh no, the limit is per account anyway (i.e. @webmozart)

**Comment by webmozart** [comment]
Here's another tweak to improve the speed of the --prefer-lowest build now that PHP 7 is stable: https://github.com/puli/repository/pull/84

**Comment by EmanueleMinotto** [comment]
Shouldn't the appveyor.yml file contain the cache setting `%LOCALAPPDATA%\Composer\files -> appveyor.yml` too?

**Comment by webmozart** [comment]
What do you think @nicolasgrekas? I think you removed it from Symfony's configuration on purpose?

**Comment by nicolas-grekas** [comment]
the appveyor cache is only 100Mb, without regular cleaning it could get full quickly
I've no strong opinion on this, you decide on your own. It the perg gain significant enough?

**Comment by webmozart** [comment]
One could regularly clear the caches manually to prevent this by using API calls: https://github.com/appveyor/ci/issues/207 Sounds a bit complicated though and I'm not sure whether it's worth it.
