### ISSUE TITLE
puli self-update fails

### ISSUE THREAD

**Issue by gossi** [puli/issues#175]
Another time the self-update fails:

```
$ puli self-update
fatal: file_get_contents(): Peer certificate CN=`*.s3.amazonaws.com' did not match expected CN=`github.com'
```

with:

```
$ puli -V
Puli version 1.0.0-beta9
```

**Comment by webmozart** [comment]
Hi! Thank you for reporting this issue. You're very likely using PHP < 5.6. In beta 9, the self-update does not work for that version. In beta 10, that is fixed.

I recommend to use the installer instead this time:

~~~
$ curl https://puli.io/installer | php
~~~
