### ISSUE TITLE
Puli is broken when updating to the last versions

### ISSUE THREAD

**Issue by mnapoli** [puli/issues#181]
Requiring last Puli betas yields the following errors:

```
Class 'Webmozart\KeyValueStore\JsonFileStore' not found

/.../.puli/GeneratedPuliFactory.php:41
```

I'm guessing this is a known issue given [this tweet](https://twitter.com/PuliPHP/status/685132540588507137). Requiring the recommended package now leads to the following error:

```
InvalidArgumentException: The flags must be an integer. Got: boolean

/.../vendor/webmozart/assert/src/Assert.php:149
/.../vendor/webmozart/key-value-store/src/JsonFileStore.php:119
/.../.puli/GeneratedPuliFactory.php:41
```

Line 41 of the generated puli factory:

```php
$store = new JsonFileStore(__DIR__.'/path-mappings.json', true);
```

(notice the `true`)

What JsonFileStore expects:

```php
    public function __construct($path, $flags = 0)
    {
        Assert::string($path, 'The path must be a string. Got: %s');
        Assert::notEmpty($path, 'The path must not be empty.');
        Assert::integer($flags, 'The flags must be an integer. Got: %s');
```

I can't find where the `GeneratedPuliFactory` is created to fix this?

**Comment by mnapoli** [comment]
FYI changing the `true` to a `0` leads to the following error:

```
Error: Class 'Webmozart\Json\JsonEncoder' not found
```

This doesn't seem to be a solution.

**Comment by webmozart** [comment]
@mnapoli Thanks for the report. I suggest to switch to the `json` repository implementation:

```
$ puli config repository.type json
```

Right now, you seem to be using the `key-value-store` implementation with a `json-file` store as backend.

**Comment by mnapoli** [comment]
:+1: thanks I'll try that, what is the "repository implementation"? Is it `puli.json`?

And will it be enabled by default for new projects from now on?

**Comment by webmozart** [comment]
@mnapoli Yes, `json` is the default. You can actually switch to default using:

```php
$ puli config -r|--reset respository.type
```

The "repository implementation" is the implementation of `ResourceRepository` that is used to store the resources of your modules. Right now, you are using `KeyValueStoreRepository`, but in the latest release of [puli/repository](/puli/repository) we added a much better `JsonRepository` implementation.

**Comment by mnapoli** [comment]
Should this issue be closed then?

**Comment by webmozart** [comment]
Let me check whether this issue is resolved in master first.
