### ISSUE TITLE
Twig extension notifies Url Generator is missing when it isn't

### ISSUE THREAD

**Issue by gossi** [puli/issues#182]
I came across this one, when I got the error that the url generator package is missing. AlthoughI had the `puli/url-generator` package installed and get the warning about a non-installed url-generator - huh? My problem was I didn't pass the url-generator as second parameter to the `PuliExtension`.

Before: `new PuliExtension($repo)`
After: `new PuliExtension($repo, $discovery)`

Also docs don't mention the second parameter as required for use in conjunction with `resource_url()` twig function. I think you find a smart solution to that :smiley:

Ref #98

**Comment by webmozart** [comment]
Thanks for reporting this issue @gossi! We'll try to find a better message here.
