### ISSUE TITLE
[Question] Is there a list of packages that support puli?

### ISSUE THREAD

**Issue by Petah** [puli/issues#189]

**Comment by tgalopin** [comment]
There is no official list, however you can quite easily find OSS projects with a Github search: https://github.com/search?q=filename%3Apuli.json&type=Code&utf8=%E2%9C%93

Some other are working on a Puli implementation:
- https://github.com/PHP-DI/Kernel
- https://github.com/FriendsOfSymfony/FOSMessage/pull/17
- probably others I don't know

But what's interesting with Puli is that by trying to implement framework-agnotic modules, we developed different useful tools that can be use as standalone (mainly discovery and repository). For instance, using the repository and puli.js with Gulp/Grunt, you can quite easily implement a clean organization of your assets, with a PHP integration. With the discovery, you can easily create a "Driver" system to find classes implementing a given interface.

**Comment by webmozart** [comment]
I hope @tgalopin's comment answered your question! :)
