### ISSUE TITLE
Puli/repository does not use master branch

### ISSUE THREAD

**Issue by Nyholm** [puli/issues#197]
There is probably an easy answer to this question but I cant find it. Why do we have a 1.0 branch on puli/repository that we use instead of the master branch?

**Comment by webmozart** [comment]
Hi @Nyholm! There used to be features in the Repository component that were taken out before the first release. Hence I created a 1.0 branch and kept the master branch with the features that were taken out. Given that the two branches diverged, I think it makes sense to discard the master branch now and rename 1.0 to master.

**Comment by Nyholm** [comment]
👍

**Comment by webmozart** [comment]
This is fixed now
