### ISSUE TITLE
Attaching to repositories and PHPCR

### ISSUE THREAD

**Issue by dantleech** [puli/issues#20]
Hi,

I am implementing the new `Resource` API - what is the use case for attaching to repositories?

**Comment by dantleech** [comment]
I made some comments on the PR I am working on: https://github.com/symfony-cmf/Resource/pull/2

**Comment by webmozart** [comment]
As I replied in the PR, you can add any kind of resource to any kind of repository. A use case is caching:

```php
$repo = new FilesystemRepository();

// Recursively add all resources
$repo->add('/', $phpcrRepo->get('/'));
```

I recommend to extend GenericResource to inherit implementations for all the general-purpose methods of the Resource interface.

**Comment by webmozart** [comment]
Is this still an issue?

**Comment by dantleech** [comment]
So just to check that I understand:

If a `PhpcrResource` implements the `BodyResource` we can transfer it to a `FilesystemRepository`

If we implement something like `KeyValue` resource then we could transfer `PhpcrResource` to a `MongoDBRepository` for instance.

Sounds pretty good.

**Comment by webmozart** [comment]
Yes exactly :)
