### ISSUE TITLE
Twig Error: Node "parent" does not exist for Node "Twig_Node_Module".

### ISSUE THREAD

**Issue by gossi** [puli/issues#204]
I use the puli twig extension for `resource_url()`. I updated twig to recent version `1.26.1`. Since then my templates report this error:

> [Twig_Error_Syntax] An exception has been thrown during the compilation of a template ("Node "parent" does not exist for Node "Twig_Node_Module".") in "/path/to/template.twig"

I tried a blank template and the error persists, so I guess it is coming from the puli extension (as there is nothing else left from my side). In that case, a quick-fix is appreciated ;)

**Comment by gossi** [comment]
I reverted back to twig version `1.24.*`, which works. It is something, that is introduced in version `1.25.0`.

**Comment by mnapoli** [comment]
Same here (with a blank template too), thanks @gossi for the temporary workaround. The [changelog](https://github.com/twigphp/Twig/blob/1.x/CHANGELOG) for `1.25.0`:
- changed the way we store template source in template classes
- removed usage of realpath in cache keys
- fixed Twig cache sharing when used with different versions of PHP
- removed embed parent workaround for simple use cases
- deprecated the ability to store non Node instances in Node::$nodes
- deprecated Twig_Environment::getLexer(), Twig_Environment::getParser(), Twig_Environment::getCompiler()
- deprecated Twig_Compiler::getFilename()

I wonder if it is that change: https://github.com/twigphp/Twig/commit/0da2dd4eba5f0c1cf40305446444c018eee6e9c3 (`removed embed parent workaround for simple use cases`)

``` diff
-        $module->setNode('parent', $parent);
+        if ($fakeParentToken === $parentToken) {
+            $module->setNode('parent', $parent);
+        }
```

The node `parent` is not always set anymore, and maybe that's what causing the error. I'll try to have a look in more details but it's already late…

**Comment by mnapoli** [comment]
I've opened a PR with a fix: https://github.com/puli/twig-extension/pull/23

**Comment by fabpot** [comment]
I think this is due to this one instead: "deprecated the ability to store non Node instances in Node::$nodes". So, indeed, the `parent` node does not exist when there is no parent. I've just submitted a patch on Puli (#24) that works with all versions of Twig, but as I'm not a Puli user, please check that it indeed fixes this issue.
