### ISSUE TITLE
Globbing

### ISSUE THREAD

**Issue by temp** [puli/issues#35]
Is it possible to NOT glob like git?

Example resources:
/app/main.js
/app/lib/something.js

When I ->find("/app/\*.js") I still get both files, not only the first.
Maybe a globbing like ant with different meanings for \*\* and \* would have been a better option?

**Comment by webmozart** [comment]
> different meanings for * and *

Could you clarify?

**Comment by temp** [comment]
Sorry, didn't see the formatting issues. I meant \* and \*\*
In ant there is a differency between /app/\*.js and /app/\*\*.js, first resolves to js files in /app, second to all js files anywhere under /app.

**Comment by webmozart** [comment]
This was implemented in [webmozart/glob 1.0.0-beta2](https://github.com/webmozart/glob/releases/tag/1.0.0-beta2).

**Comment by temp** [comment]
Awesome!
Will switch to beta2 tomorrow, and test.
