### ISSUE TITLE
Remove disabled bindings that point to non-existing UUIDs

### ISSUE THREAD

**Issue by temp** [puli/issues#36]
Puli should remove obsolete disabled bindings.

**Comment by webmozart** [comment]
What do you mean by "obsolete" bindings?

**Comment by webmozart** [comment]
ping

**Comment by temp** [comment]
We talked about this some time ago, I removed some bindings on my side, but puli threw a warning because it didn't find them anymore. Maybe this has been resolved over the months? Otherweise I can provide a test case.

**Comment by webmozart** [comment]
I don't think this has been resolved. It would be great if you could provide a test case and maybe even a fix? :)

**Comment by temp** [comment]
Fishing for pull requests? ;-)
Will do if I find the time.

**Comment by webmozart** [comment]
:heart_eyes_cat:

**Comment by webmozart** [comment]
This is fixed now! \o/
