### ISSUE TITLE
Major error with symlinks on windows

### ISSUE THREAD

**Issue by temp** [puli/issues#37]
We just had a weird error with puli on windows.
Suddenly, the contents of Resources in several composer installed packages where missing.
After some research, we found out that this happened in packages that had puli resources.
We updated the missing files, and did a composer update - and again, files where deleted.

It _seems_ to be a problem with symlinks on windows. On my Mac everything works fine.
We tried some things on the command line, and found out that a call to file-delete (del) on a folder-symlink removes all files inside the symlink-target-folder. A folder-delete (rmdir) worked as expected, and removed the folder-symlink.
We looked through the puli code that handles the symlinks, but didn't find anything related.
Maybe this is even a problem in symfony-filesystem.

We tried to produce a testcase, but couldn't reproduce the error that happened with puli.

Any ideas?

**Comment by webmozart** [comment]
Weird. At least you can reproduce the error on the computer/project you just described, right?

Puli uses the Symfony Filesystem component to remove resources (see FilesystemRepository.php:334). Could you step through your debugger and see how often `remove()` is called on this line and with what arguments? It *should* be called only once for the removed directory (link).

The Filesystem component actually deletes directory links with `rmdir()`, so this is weird. Could you debug this some more and try to find the problem?

**Comment by temp** [comment]
Yes, will do. But earliest on monday. Will report afterwards.

**Comment by webmozart** [comment]
Any news on this issue?

**Comment by temp** [comment]
Will try to check tomorrow - had no problems on my private windows pc at home.
My collegue at work still has the issue, though.

**Comment by webmozart** [comment]
Any news?

**Comment by temp** [comment]
Sorry, colleague left for vacation without a chance to test :(

**Comment by webmozart** [comment]
Any news?

**Comment by temp** [comment]
We tried it again on my colleagues windows machine, and did not experience any problems.
No vanishing vendor-files anymore.
