### ISSUE TITLE
find with regex pattern

### ISSUE THREAD

**Issue by digitalkaoz** [puli/issues#38]
i would love to see a feature like this:

```php
$repo = new InMemoryRepository();
$repo->add('/assets', new DirectoryResource('/path/to/assets'));

$images = $repo->find('~^[^/]+\.{jpeg,gif,png}$~');
$js = $repo->find('~^[^/]+\.{js,jsx}$~');
```

so basicly allow searching by some sort of regex (wether its the glob regex syntax or real pcre syntax)

**Comment by webmozart** [comment]
Thanks for opening this issue! Since `find()` (and similar methods) support a parameter `$language`, this feature would be usable like so:

```php
$images = $repo->find('~^[^/]+\.{jpeg,gif,png}$~', 'regex');
```

Or when binding on the command line:

```
$ puli bind --language=regex "~^[^/]+\.{jpeg,gif,png}$~" my/type
```

Sounds good?

**Comment by digitalkaoz** [comment]
thats exactly what i had in mind...

**Comment by webmozart** [comment]
Ok. I don't think this will make it into 1.0 as we're past the feature freeze, but I'll implement this for 1.1. :)

**Comment by digitalkaoz** [comment]
i think that will be ok, i have a somewhat working hack here, but nothing i like to contribute. if i find time i can publish some code, but i think you have exactly in mind how it needs to be implemented ;)

**Comment by webmozart** [comment]
For your information: The glob alternative syntax `{a,b,c}` was added to https://github.com/webmozart/glob recently, so you can do this now:

```php
$images = $repo->find('**.{jpeg,gif,png}');
```

which is equivalent to the above regular expression.

**Comment by digitalkaoz** [comment]
**wh00pwh00p** :+1:

**Comment by webmozart** [comment]
Given my above comment, I'll close this issue for the time being. I don't think that adding regular expression support is very important now.
