### ISSUE TITLE
Object resource?

### ISSUE THREAD

**Issue by dantleech** [puli/issues#41]
Would it make sense to add a resource interface `ObjectResource`?

For instance, I am creating a Resource based CMF Router. The Resource's returned can be PhpcrOdmResource, PhpcrResource or DoctrineOrmResource. These currently have the methods `getDocument`, `getNode` and `getEntity` respectively. The underlying resources must be of type `Route`.

It is therefore desirable to have a `getObject` method either in addition or instead of the domain oriented method names.

**Comment by webmozart** [comment]
Do you have any use case in mind where an `ObjectResource` could be used interchangeably, independent of whether the underlying object is a document, node or entity?

To make this a little more generic, I could imagine adding a `getPayload()` method to the `Resource` interface which returns arbitrary, implementation-specific data.

**Comment by dantleech** [comment]
Yeah, the use case is the router. All that matters is that the object extends the `Symfony\Component\Routing\Route` object. So it could be a ORM-like object or a Route loaded from the standard routing system.

`getPayload` would mean that I could not guarantee that the return value is an object.

**Comment by webmozart** [comment]
You'd need to check whether the object is a route anyway, no?

**Comment by dantleech** [comment]
yeah, but I would imagine having to do the following:

````php
$payload = $resource->getPayload();

if (!is_object($payload)) {
    throw new Exception('...');
}

if (!$payload instance of Route) {
   ...
}
````

**Comment by webmozart** [comment]
```php
$route = $resource->getPayload();

if (!$route instanceof Route) {
    throw new InvalidArgumentException('Expected a Route').
}

// do it
```

sounds simple enough to me no? :) You can't *guarantee* anyway that a method returns an object ever, even if the docblock says so.

**Comment by dantleech** [comment]
Hmm, right you are. I tested with `var_dump('asd' instanceof \stdClass)` but using a variable works as expected.

**Comment by dantleech** [comment]
So .. I think +1 for getPayload :)

**Comment by webmozart** [comment]
There you go. :)

**Comment by dantleech** [comment]
heh. quick work :P thanks.
