### ISSUE TITLE
[Assetic Extension] undefined variable $repoDir

### ISSUE THREAD

**Issue by Tobion** [puli/issues#43]
`$repoDir` in https://github.com/puli/assetic-extension/blob/master/src/Util/PuliCssUtils.php#L49 does not seem to exist

**Comment by webmozart** [comment]
Thanks for reporting this issue! The PuliCssUtils class is work in progress.

**Comment by webmozart** [comment]
Since Puli by now tries to integrate with frontend tools like Gulp, support for Assetic is not going to be continued.
