### ISSUE TITLE
Error with puli twig loader

### ISSUE THREAD

**Issue by temp** [puli/issues#46]
I don't know wether or not this is an error - when the template extension is installed, and the requested template isn't found, the puli template loader throws an error.
Shouldn't it simply return without a loaded template, and have the chain loader decide wether or not the template was not found?
Maybe there are additional template loaders after puli...

**Comment by stof** [comment]
@temp this is the expected behavior of Twig loaders. they should throw a Twig_Error_Loader when they cannot load a template. The Twig_Loader_Chain is aware of that and catches these exceptions to move to the next one.

**Comment by temp** [comment]
Ok, thanks for the clarification.
So the Twig_Loader_Chain throws the exception of the last tried loader?
Was just confused that I'm getting a puli loader exception when trying to load a nonexistant template "::article.html.twig".
