### ISSUE TITLE
Puli documentation and usage

### ISSUE THREAD

**Issue by harikt** [puli/issues#52]
Hi @webmozart ,

I was trying puli after some time. I had some difficulties to make things work in my experiments. I know it may be my fault . Would like to share my failures

1. The doc mentions about http://docs.puli.io/en/latest/getting-started.html#loading-the-puli-factory .

Wonder where we should create the file and do we need to execute this file or not . May be you need to comment out in the code the file name with path that people will find it helpful ?

2. What I am trying to achieve

The goal of me trying puli is to build reusage package whose css / images / js can be pushed to public folder . So the documentation I am looking should be http://docs.puli.io/en/latest/getting-started.html#directory-layout-recommendation .

Let's say before I package and push to composer I need to try this particular package will install the file in the public folder of the framework.

What I did so far. Installed puli and deps.

```json
{
    "require": {
        "puli/repository": "~1.0",
        "puli/discovery": "~1.0"
    },
    "require-dev": {
        "puli/cli": "~1.0"
    },
    "minimum-stability": "beta"
}
```

Created a package folder 

```
package
├── config
├── public
│   ├── css
│   │   ├── main.css
│   │   └── reset.css
│   ├── images
│   └── js
│       └── app.js
├── src
│   └── Hello.php
└── views
    └── hello.php
```

Added a `find.php` file with contents 

```php
<?php
// find.php
require __DIR__ . '/vendor/autoload.php';

$factoryClass = PULI_FACTORY_CLASS;
$factory = new $factoryClass();
$repo = $factory->createRepository();
```

But I think I am missing some other steps also. The last goal after I created the package is the framework should do something .

Say my document root is `web` .
Thanks!

**Comment by webmozart** [comment]
Hi @harikt,

Thank you for the feedback! :)

> Wonder where we should create the file

How you create the `$factory` and the `$repo` objects depends on your application. If it's a simple script, you can simply create them on top of the script, as you did. If it's a more complex application, you might want to use a Dependency Injection Container which returns the objects something like this:

```php
// loads the factory and the repository
$repo = $container->get('puli.repository');
```

> Created a package folder

You should put the `config`, `public` and `views` directories into a subdirectory `res`. Then you have to map the directory to a Puli path with the command line (as described in [Mapping Resources](http://docs.puli.io/en/latest/mapping-resources.html)). Given your package is called `harikt/demo`, the path should be:

```
$ puli map /harikt/demo res
```

At last, you should read [Web Resources](http://docs.puli.io/en/latest/web-resources.html) to learn how to handle your assets with Puli.

Hope this helps! :)

**Comment by webmozart** [comment]
I will try to improve the documentation to better answer your question.

**Comment by harikt** [comment]
I am also looking into http://docs.puli.io/en/latest/web-resources.html . So far I did 

```
$ php vendor/bin/puli plugin install Puli\\WebResourcePlugin\\Api\\WebResourcePlugin
$ mkdir web
$ php vendor/bin/puli target add local web
$ ls
composer.json  composer.lock  factory.php  package  puli.json  vendor web
$ php vendor/bin/puli web add /package/public /
fatal: Did not find any resources to bind for query "/package/public{,/**}".
```

Also interested to know each and every time we need to run puli cli to map the resource ?

If it can do this as a composer post install hook may be good.

I wish to bring puli if possible to a framework skelton https://github.com/harikt/conduit-skelton .

**Comment by webmozart** [comment]
Can you run `puli map` and `puli tree` and show me the output?

> Also interested to know each and every time we need to run puli cli to map the resource

No. If you map `/package` to your `res` directory, then all files in that directory are mapped too. So you should have to run `puli map` only once or twice per package, although I'd like to simplify that in a later version through a `puli init` command.

**Comment by harikt** [comment]
>
> Can you run puli map and puli tree and show me the output?
>

$ php vendor/bin/puli map
$ php vendor/bin/puli tree
/

0 resources

>  Also interested to know each and every time we need to run puli cli to
> map the resource
>
> No. If you map /package to your res directory, then all files in that
> directory are mapped too. So you should have to run puli map only once or
> twice per package, although I'd like to simplify that in a later version
> through a puli init command.
>
Please note that the package is not installed via composer.

It is still a path to a folder.

Thanks

**Comment by webmozart** [comment]
It seems you didn't add a mapping yet, otherwise `puli map` would show some output. I created a ticket to improve the output of that command: #53.

You should run:

```
puli map /package res
```

to map the Puli path `/package` to the directory `res` (given that directory exists).

**Comment by harikt** [comment]
Hi @webmozart ,

Here is my package folder .

```
package
├── config
├── res
│   ├── public
│   │   ├── css
│   │   │   ├── main.css
│   │   │   └── reset.css
│   │   ├── images
│   │   └── js
│   │       └── app.js
│   └── views
│       └── hello.php
└── src
    └── Hello.php
```

Here is the o/p of the map command.

```
$ php vendor/bin/puli map /package res
fatal: The path res mapped to /package by package "__root__" does not exist.
```

**Comment by webmozart** [comment]
Ah, now I see the confusion :) I expect your package to look something like this:

```
package
├── res
│   ├── config
│   ├── public
│   │   ├── css
│   │   │   ├── main.css
│   │   │   └── reset.css
│   │   ├── images
│   │   └── js
│   │       └── app.js
│   └── views
│       └── hello.php
├── src
│   └── Hello.php
├── vendor
│   └── ...
├── composer.json
└── puli.json
```

So you are working *inside* the `package` folder. Otherwise it's natural that the `res` directory is not found. :)

**Comment by harikt** [comment]
nope. See I am inside a directory puli.  The ls command shows 

```
$ ls
composer.json  composer.lock  factory.php  package  puli.json  vendor  web
```

The package folder is what I created for testing . Wanted to see whether the public file will be pushed to web folder.

**Comment by webmozart** [comment]
Yes, I am just telling you what a typical package will look like :) However, you can work with your directory structure if you map your paths accordingly:

```
puli map /package package/res
```

**Comment by harikt** [comment]
It seems more work than I expected to run Puli :( .

```
php vendor/bin/puli web add package/res/public / 
fatal: The glob "package/res/public{,/**}" is not absolute.
$ php vendor/bin/puli target add local web        $ 
$ php vendor/bin/puli web add package/res/public /
fatal: The glob "package/res/public{,/**}" is not absolute.
$ php vendor/bin/puli web add "package/res/public/{css,js}" /
fatal: The glob "package/res/public/{css,js}{,/**}" is not absolute.
$ php vendor/bin/puli web add "package/res/public/{css,js}"  
fatal: Not enough arguments.
$ php vendor/bin/puli web add "package/res/public/{css,js}" web 
fatal: The glob "package/res/public/{css,js}{,/**}" is not absolute.
```

**Comment by webmozart** [comment]
I'm sorry for your bad experience. I definitely need to work on the documentation and the error messages. 

To improve your experience and learn more easily, I *really* recommend you to create the directory structure I showed you before. Once you understand Puli, you can still customize the directory structure the way you like.

Let me repeat the directory structure:

```
package
├── res
│   ├── config
│   ├── public
│   │   ├── css
│   │   │   ├── main.css
│   │   │   └── reset.css
│   │   ├── images
│   │   └── js
│   │       └── app.js
│   └── views
│       └── hello.php
├── src
│   └── Hello.php
├── vendor
│   └── ...
├── composer.json
└── puli.json
```

The directory `package` is the root directory of your project.

Next, you need to understand that there's a difference between two kinds of paths:

* Regular filesystem paths, such as `res/public/css/main.css`
* *Puli paths*, such as `/package/public/css/main.css`

With `puli map`, you map a Puli path to a filesystem path:

```
puli map /package res
```

Except for the `map` command, all other commands work with Puli paths. You can display the resources in your Puli repository with `puli ls` and `puli tree`, which will also show you the Puli paths of the resources.

Assuming you created the above mapping, you can create the web mapping now:

```
puli web add /package/public /
```

Note the leading `/`. We are passing a Puli path, and (at least on the CLI) Puli paths are always absolute.

If you want, you can join #puliphp on Freenode (IRC), there I can help you more.

**Comment by webmozart** [comment]
Hi again, I created a demo application that should help you experiment with Puli more easily:
https://github.com/puli/demo-application

**Comment by harikt** [comment]
Thanks @webmozart .

If there was some steps that you have worked to make that could have helped. How the puli.json was created etc.

**Comment by webmozart** [comment]
@harikt It's all there in the documentation. But apparently the docs are not good enough, I'll work on that.

**Comment by harikt** [comment]
@webmozart the docs are there. But all spread across :-/ .

**Comment by webmozart** [comment]
I added reproduction steps to the README of the demo app now. Does this help?

**Comment by harikt** [comment]
Thank you @webmozart .  I will give it a try once again though I tend to look at my own solution built  earlier.

**Comment by webmozart** [comment]
I improved the [Getting Started guide](http://docs.puli.io/en/latest/getting-started.html) to address your concerns now. Hopefully the guide is suited better now to give a quick introduction into Puli.

**Comment by harikt** [comment]
Thank you @webmozart .

**Comment by odhiambo123** [comment]
is puli still maintained?

**Comment by Nyholm** [comment]
Sure, Have you found an issue?

**Comment by odhiambo123** [comment]
when I try to run npm install on the above demo application after cloning it, I get an error

dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicudata.60.1.dylib
  Referenced from: /usr/local/bin/node
  Reason: image not found
Abort trap: 6

**Comment by odhiambo123** [comment]
Developers-iMac:demo-application developer$ npm install
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated pangyp@2.3.3: use node-gyp@3+ instead
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js

> node-sass@2.1.1 install /Users/developer/demo-application/node_modules/node-sass
> node scripts/install.js

WARN invalid config loglevel="notice"
Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.1.1/darwin-x64-node-9.3/binding.node

> node-sass@2.1.1 postinstall /Users/developer/demo-application/node_modules/node-sass
> node scripts/build.js

module.js:557
    throw err;
    ^

Error: Cannot find module '/Users/developer/demo-application/node_modules/node-sass/node_modules/pangyp/bin/node-gyp'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:618:3
Build failed
npm notice created a lockfile as package-lock.json. You should commit this file.
added 462 packages in 55.301s

**Comment by odhiambo123** [comment]
the above log is after I updated node and then trying to run the demo application referenced in the discussion above.

**Comment by Nyholm** [comment]
That sure sounds like a node error. Why do you think it is related to Puli.. or PHP?
