### ISSUE TITLE
Support for runtime configuration.

### ISSUE THREAD

**Issue by patternseek** [puli/issues#63]
Hi,

There are various situations where we might want to include resources dynamically so it would be really useful to be able to augment the mappings in the puli.json with additional mappings added at runtime, similarly to Composer's addPsr4() method. 

Cheers.

**Comment by webmozart** [comment]
Hi :)

I don't know details about your use case, but you can achieve this in various ways:

* If you want to add mappings to the puli.json of a project based on your own logic, you can uses the [Puli Manager API](/puli/manager) to do that.

* If you want to run that logic automatically (e.g. during "puli build"), you can create a [Puli Plugin](https://github.com/puli/manager/blob/master/src/Api/PuliPlugin.php) that listens to the corresponding [event](https://github.com/puli/manager/blob/master/src/Api/Event/PuliEvents.php) (not many for now, but to be extended on demand).

* If you want to have truly dynamic resources (e.g. loaded from the database), you can implement a custom [Resource Repository](https://github.com/puli/repository/blob/1.0/src/Api/ResourceRepository.php). This repository can be hooked into Puli by extending the GeneratedFactory class in your /.puli/ directory and overriding the createRepository() method. You need to tell Puli to use your class by running `puli config factory.in.class Your\Factory\Class`.

Does that solve your question?

Unfortunately there is not much documentation on these advanced features yet, but if you have questions, don't hesitate to ask!

**Comment by patternseek** [comment]
Thanks for the quick reply! :)

Sounds like the Puli Manager API is probably the closest to what I'm looking except the difference would be that ideally the additional paths would be held in memory only rather than persisted to the puli.json.

I think this would be generally useful but I'll explain my specific case anyway. Basically I have a number of modules that get included in the app at build time but who shouldn't be included in the puli.json in git. For the same reason they can't be included in the framework/app's composer.json. So ideally the app would be able to add in mappings for them dynamically based on which modules are present.

Currently I'm looking at fixing it with a bit of a hack which is two write a script that calls Puli CLI to build puli.json at build time, and add puli.json to .gitignore. Not quite what you had in mind for Puli I know! But it's still very useful to me to be able to abstract the file paths.

**Comment by webmozart** [comment]
I see. In that case, listen to one of the *_BUILD_REPOSITORY events that I just added (see the referenced commits) and use the [Puli Repository API](https://github.com/puli/repository/blob/1.0/src/Api/EditableRepository.php) directly. Then the resources are added to the repository everytime that the repository is built (i.e. during `composer update` and `puli build`), but they are not added to puli.json.

You can add an event listener by implementing the [PuliPlugin](https://github.com/puli/manager/blob/master/src/Api/PuliPlugin.php) interface and calling:

```
$ puli plugin install My\\Plugin\\Class
```

**Comment by patternseek** [comment]
Oh wow, you're a star thanks!

**Comment by webmozart** [comment]
I suppose I can close this :) If you have any problems, don't hesitate to reopen or open a new issue.

**Comment by patternseek** [comment]
Yep thanks.
