### ISSUE TITLE
private method PathCommandHandler::applyMergeStatements() not used.

### ISSUE THREAD

**Issue by patternseek** [puli/issues#64]
Attempting to mount multiple physical paths on a single logical path I was getting errors like this when attempting to use "+" to append a path:

```sh
puli path map /module/core/config +modules/core/conf                                                     
fatal: The path "/module/core/config" is already mapped in package "patternseek/agile".
```
The mapping may look odd but it's because I'm transitioning a bunch of legacy code.

I had a poke around and came across PathCommandHandler::applyMergeStatements() which looks like it's intended to handle appending and removing phys paths from a logical path and my IDE pointed out the method is unused.

**Comment by webmozart** [comment]
Ah, this is a documentation issue. This functionality was moved to the "puli path update" command.

```
puli path update /module/core/config --add modules/core/conf      
```

**Comment by webmozart** [comment]
The applyMergeStatements() method is dead code and should be removed.

**Comment by patternseek** [comment]
Thanks.

**Comment by webmozart** [comment]
The method was removed, the docs are updated now.
