### ISSUE TITLE
asset-plugin 1.0 and webmozart/expression required by current puli beta are incompatible

### ISSUE THREAD

**Issue by patternseek** [puli/issues#75]
DiscoveryAssetManager:186 references the obsolete Expr:valid():

return $this->findAssetMappings(Expr::valid());

**Comment by webmozart** [comment]
Hi @patternseek! The Asset Plugin has been merged into puli/cli and puli/manager and is deprecated. You don't need to install the plugin anymore as of the latest beta.

I'm currently updating the documentation to reflect that.

**Comment by patternseek** [comment]
Great thanks :)

**Comment by patternseek** [comment]
Sorry to comment on a closed ticket but can you give me a brief overview of how to handle assets now? "puli asset" no longer works so I'm not sure where to go.

**Comment by webmozart** [comment]
I just published the updated documentation :) http://docs.puli.io/en/latest/url-generator/introduction.html

**Comment by patternseek** [comment]
Perfect thanks.
