### ISSUE TITLE
Path mapping gets very slow once a mapping contains a largee number of files.

### ISSUE THREAD

**Issue by patternseek** [puli/issues#77]
Hi,
Me again sorry ;)

puli map can get really slow once a given mapping contains quite a few files. Here's an example when appending a small directory to a mapping that's already quite large:

```
 ❯ time puli map -u /app/lib --add modules/bugReport/lib
noglob puli map -u /app/lib --add modules/bugReport/lib  1953.20s user 6.64s system 99% cpu 32:42.87 total
>>> elapsed time 32m43s
```
This is just one of quite a few mappings I need to update periodically.

The problem is in SyncRepositoryPath::collectEnabledFilesystemPaths() which can end up getting called a *lot* with its recursion.

I have a bit of a hack that improves the runtime for my test case from 32m to ~6m. It's not really a solution as even 6m is pretty excessive. It works on the basis that Path::isBasePath() and canonicalize() have to do additional work for things like Windows paths that aren't necessary for a repository path and so shortcuts that test where possible. I'm not proposing this, hence no PR, but I think it's useful to see. Before:

```php
            // Check mappings for the passed repository path or any of its
            // nested paths
            if ($repositoryPath !== $mappedPath && !Path::isBasePath($repositoryPath, $mappedPath)) {
                continue;
            }
```
After:
```php
            // Check mappings for the passed repository path or any of its
            // nested paths
            if( $repositoryPath !== $mappedPath
                && (false === strstr( $repositoryPath, "../" ) )
                && (false === strstr( $mappedPath, "../" ) )
                && (strpos( $mappedPath, $repositoryPath  ) !== 0)
            ){
                continue;
            }
            if ($repositoryPath !== $mappedPath && !Path::isBasePath($repositoryPath, $mappedPath)) {
                continue;
            }
```
This passes the Manager test suite and gives the following:
```
 ❯ time puli map -u /app/lib --add modules/bugReport/lib
noglob puli map -u /app/lib --add modules/bugReport/lib  353.18s user 0.47s system 100% cpu 5:53.54 total
>>> elapsed time 5m54s
```
Anyway more useful would be to reduce the amount of work that collectEnabledFilesystemPaths() has to do but I've not had much luck working out how to do that given that I'm navigating a foreign codebase. I see more or less what it's doing but I'm not getting it well enough to be able to see any useful way to reduce the work it's doing. So I'm hoping you might have an idea in that direction.

**Comment by webmozart** [comment]
Hi @patternseek, thank you for the report!

Did you try the latest dev version? This should have been fixed or at least improved in puli/manager#3.

**Comment by patternseek** [comment]
Yeah this is after that optimisation is applied unfortunately.

**Comment by webmozart** [comment]
Too bad :) Ok, I'll investigate this issue ASAP.

**Comment by webmozart** [comment]
Largely improved by puli/manager@df5fcc56e3675ac8f5da26fac33f70e058cb9f0b, puli/manager@f68c550db474c7972249e5b13f23e38d703fd45f and puli/repository@ddd1b5274c379cb0e0279c00993a2a0ac37a91aa.
