### ISSUE TITLE
Puli build times out during composer install/update

### ISSUE THREAD

**Issue by patternseek** [puli/issues#78]
Hi,

If you have a large repository the build command can take more than 60 seconds so causes composer install and update to fail.

I created a PR to increase the timeout but I'm not sure if it slipped under your radar so I thought I'd create a ticket here.

Here's the PR: https://github.com/puli/composer-plugin/pull/12

**Comment by webmozart** [comment]
Thanks for reporting this issue! 

ref #77

**Comment by webmozart** [comment]
#77 is fixed now. Can you check whether the build command is sufficiently fast now for you?

**Comment by patternseek** [comment]
Is there a build with the changes on Packagist or do I need to manually install?

**Comment by patternseek** [comment]
Never mind, found the dev branch on Packagist sorry.

**Comment by patternseek** [comment]
❯ time puli build
noglob puli build  2.30s user 0.79s system 99% cpu 3.105 total

That's fantastic thanks so much! It was taking a little over a minute.

**Comment by webmozart** [comment]
Great :) I'll work on improving it some more as 2.3 seconds is still a lot. But the major bottleneck seems to be fixed at least.
