### ISSUE TITLE
Implement repository versioning

### ISSUE THREAD

**Issue by webmozart** [puli/issues#90]
At the moment, resource repositories don't remember the old resource when a resource is overwritten. For example:

```php
$repo->add('/batman/blog', new DirectoryResource(__DIR__.'/vendor/batman/blog/res'));
$repo->add('/batman/blog', new DirectoryResource(__DIR__.'/res/blog'));
```

If your application wants to retrieve *all* file system paths that were registered for a Puli path (mostly useful for merging overridden resources with the original ones, e.g. config files), that's not possible right now.

One generic way to solve this could be to add versions to resources:

```php
// Latest version
$resource = $repo->get('/batman/blog');
$resources[] = $resource;

while ($resource->getVersion() > 1) {
    $resource = $repo->get('/batman/blog', $resource->getVersion() - 1);
    $resources[] = $resource;
}

// merge $resources
```

I tried implementing this once, but stopped, since this is not trivial and was not too important back then. However, we need this before the stable release.

**Comment by webmozart** [comment]
cc @tgalopin @kitsunet

**Comment by tgalopin** [comment]
I think I already have a lot to do for the moment (finish the current PRs and implement sort() in the repositories). If no one else works on it in a a week or two, I'll give it a try :) .

But thanks for the proposal!

**Comment by tgalopin** [comment]
I'll start to work on that. If I have questions, I'll ask here :) .

**Comment by tgalopin** [comment]
Actually, I already have a few questions and proposals to validate :) .

To clarify how it should work: you can push multiple resources on the same path and retrieve them using a second argument of `get()` as a version number.

I have a few questions about what you have in mind:

**1. Remove**

How would the removal of a resource work? I think the best option would be:

``` php
$repository->remove('/my/path'); // Remove all versions
$repository->remove('/my/path', $versionNumber); // Remove a single version
```

**2. List children**

I suppose `listChildren()` would work the same way as `get()`, wouldn't it? Something like:

``` php
$repository->listChildren('/my/path'); // List children of last version
$repository->listChildren('/my/path', $versionNumber); // List children of given version
```

**3. Find**

Should we propose the possibility to find specific versions? I mean, something like:

``` php
$repository->find('/**/path'); // Find last resources matching the search
$repository->find('/**/path', Repository::FIRST); // Find version 1 of each resources matching the search

// Perhaps something I can't think of right now
```

**4. Decorator**

What do you think of implementing a decorator to do all this? I think versionning is quite a specific feature and honnestly, creating a decorator for it would be much easier than implementing the feature in each repository.

I'm thinking of something like:

``` php
$repository = new VersionningDecorator(new InMemoryRepository());
```

Internally, it would use the original store to track the different versions of the resource.

**5. Who store what?**

I've a problem of understanding how it should work according to what you explained: does the resource store its version? It seems weird no? Isn't the version a concept specific to a repository? I mean, if I copy a specific resource version to an empty repository, this version of the resource should become the first version in the empty repository shouldn't it?

In my opinion, all the versionning system and comparison should be handled by the repository as it's a very repository specific concept. Perhaps am I wrong about what you are thinking of the feature.

**Comment by webmozart** [comment]
Hi @tgalopin,

I don't have perfect answers to your questions - I simply don't know what the best approach is. I'll try though:

Since versions are ordered, I think it would be natural to use incrementing integers as versions. Otherwise each version would need to reference the previous version, which sounds overly complicated to me.

I don't know whether it's necessary to support passing specific versions to `remove()`, `listChildren()` and `find()`. Maybe it is, maybe it isn't?

Using a decorator is an interesting idea. However, that decorator would need to know how to construct a repository (instead of simply passing a repository), so that different repositories can be created for different versions, no?

Maybe resource versioning isn't the best solution to the problem at hand. Our basic requirements are:

* We need to efficiently fetch the latest version of a resource (99% use case).
* There needs to be a way to access previous versions of a resource. This may be slower since it's not used very often, but it should be possible at last.

What are your thoughts?

**Comment by tmaroschik** [comment]
For me versions have a connection to a temporal dimension, which is not the case here. Resources that are overridden form a directed graph. So maybe this terminology fits better: "Resource Graph" or "Variants".

**Comment by tmaroschik** [comment]
Regarding the implementation, Resources form a Stack (better naming than graph). The Resource with the stack number 0 is the currently resolved topmost Resource. Every overridden Resource gets it's stack index decremented by 1, so the next lower Resource in the stack would have the index -1.

Internally the Repositories would need to change their resource mapping from a one dimensional array to a two dimensional. But this is bad for memory footprint (profile it yourself, nested arrays scale terribly).

An alternative would be to log every change to a repository into a simple one dimensional and append only event stream where the Stack for a Resource can be derived from on demand.

**Comment by webmozart** [comment]
> For me versions have a connection to a temporal dimension, which is not the case here.

Actually, it is. If a resource is added for a path *after* another resource has already been added for that path, it will have the next higher version. So the temporal dimension is the time at which resources were added for a path.

I agree that nested arrays should be prevented if possible. Ideally, we'd have a repository that contains the latest version of each resource only so that reading is optimized in this case. However, the management of additions would be pretty complicated in this case.

Creating an append-only repository is another interesting alternative. In that case, we'd probably need to maintain index structures to optimize reading of the latest/specific versions.

**Comment by tmaroschik** [comment]
You're right. I thought about versions in regards to DDD where I would model a Resource as Aggregate Root and versions would relate to a different state in time of the same Resource. In this regard I would prefer the term Variant as it is another implementation of the same resource, not a state of the resource at a particular point in time.

Just keep the current Repositories exactly like they are, but log every change to a Change Stream (should be an own object, that is shared among repositories; could be also a good point to implement logging). Changes should be logged as simple types to allow PHP garbage collection of Resource objects.

Every Resource would get a Stack Index. Most of those will always have a Stack Index of 0. But in case you want to gather all Variants of a Resource you would call `->getVariants()' on the Resource.
It would return you a Resource Stack then which fetches all changes related to this Resource Path from the Change Stream and assemble the Stack (eventually SplStack is helpful).

This approach doesn't impact the performance of the current implementation and changes to existing Repositories & Resources are minimal. Further the Change Stream could be replaced by a "Null" Change Stream in production, when the Resource Stack functionality is not needed.

**Comment by webmozart** [comment]
That's a very good idea! I like it. Still not convinced that "variant" is easier to understand for the typical end user. The different variants of a resource are ordered, with the last one having highest, the first one having lowest priority - since it's the oldest one. The term "version" implies exactly that. The term "variant", on the other hand, does not give any information about the relation between the different variants.

**Comment by tmaroschik** [comment]
… Naming things is really the hardest task ;)

I fear that the term version is somehow occupied already by VCS. I could imagine also VCS repositories in puli where things could become ambiguous.

What do you think of "predecessors" ?

**Comment by kitsunet** [comment]
Actually you are asking the repository for PreviousMappings on a given path, how about that?

**Comment by kitsunet** [comment]
or more precisely you want "getAllMappingsFor($path)"

**Comment by tgalopin** [comment]
I really like the idea of the Change Stream, I think it's the most elegant way to implement this version system

However I did not get how you could get all the "variants" from a resource? If I understood well, the Change Stream is an independant object, which is triggered on change of a resource, so it would be the storage object of all the resources versions wouldn't it? How could a resource access its own variantes then?

**Comment by tmaroschik** [comment]
You're missing a second object in this scenario, which is the resource stack. This one fetches the changes for the particular resource path from the change stream and creates the predecessor resource objects.

So API could be Resource->getStack(), which returns a ResourceStack, a special ResourceCollection, which also contains the current Resource. The resource stack object should be first created upon the first call of the getStack method. Possibly via a ResourceStack factory, that returns the same stack for all resources in the same stack.

**Comment by tgalopin** [comment]
Okay, i tihnk I got it now. I'll start to work on that and send a PR for it so we can continue to discuss.

**Comment by tgalopin** [comment]
It's been a while now as I have quite a lot of work for the moment but I'm still planning to work on this. Please don't hesitate to start something and I'll give a hand :) .

**Comment by tgalopin** [comment]
Work in progress here: https://github.com/puli/repository/pull/54.
