### ISSUE TITLE
Require puli/composer-plugin on windows

### ISSUE THREAD

**Issue by WedgeSama** [puli/issues#93]
I just add `"puli/composer-plugin": "^1.0@beta"` to the `composer.json` file, then run `composer update`. I got a weird output:

```
Generating PULI_FACTORY_CLASS constant
Registering @ECHO OFF
SET BIN_TARGET=%~dp0/../vendor/puli/cli/bin/puli
php "%BIN_TARGET%" %* with the class-map autoloader
Looking for updated Puli packages
```
I find why. On Windows, the .bat file is run under php and not directly. So  it only print the file script content instand of print the result of the .bat exec.

After fix that, I got another error, due to Windows and its EOL. Change "\n" by PHP_EOL resolve this.

And the last one (due to Windows to?), run a command with single quotes using PuliRunner add quotes to the first and the last arguments. Using double quote work well. I try to understand why but did not found (run the command from the shell work fine both with single and double quotes).

[The related PR](https://github.com/puli/composer-plugin/pull/14)

**Comment by temp** [comment]
This should be resolved with PR puli/composer-plugin#18, as stated in #102.
