### ISSUE TITLE
Add JSON migrations

### ISSUE THREAD

**Issue by webmozart** [puli/issues#96]
We need a mechanism to migrate puli.json files between different versions. The idea is that we can make BC breaking changes to puli.json that can easily be fixed in user projects. I don't want to do such changes anymore once 1.0 is released, but until then, such changes will be needed a few times. I would like to simplify upgrades for early adopters so that we get more feedback from real world projects.

The puli.json file contains a "version" key that currently stores the version "1.0". This version should be reset to "0.1" for the next beta release. The basic idea is:

* The "puli" command should be able to read puli.json files of different versions.
* The "puli" command writes puli.json files in their current version.
* The "puli upgrade" command can be used to upgrade puli.json files to newer versions.
* A warning should be displayed in the CLI if the puli.json of the root package has an outdated version.

Technically we need to solve the following issues:

* Rename `PackageJsonSerializer` to `PackageJson01Serializer`. This serializer reads and creates JSON structures in version 0.1.
* Add a new `PackageJsonSerializer` which inspects the version in the JSON, delegates to the appropriate serializer for that version or fails if the version is not supported.
* Add interface `Puli\Manager\Api\Migration\JsonMigration` with two methods `up($json)` and `down($json)`.
* Add command `puli upgrade` which takes the puli.json of the root package and applies all migrations from its current up to the most recent (or a specific given) version. Such migration classes could be named `Puli\Manager\Package\Migration\PackageJson01To02Migration`.

**Comment by stof** [comment]
another thing to add in basic idea: the puli command should fail if the puli.json contains an unsupported version (particularly useful in case your own puli version is older than the puli version used to generate the file)

**Comment by webmozart** [comment]
@stof that's already the case :)
