### ISSUE TITLE
Fix Windows symlink time information

### ISSUE THREAD

**Issue by WedgeSama** [puli/issues#99]
On Windows, symlink does not work like on Unix, the OS think it is a real file like another. So for time operations, it only see changes on the symlink file and not the original one. That mean fileXtime functions get info about the symlink file too.

So if you make some changes in the original file, Puli will not seen anything if this file is register in the repository as a symlink. It work as espected for files in a symlink directory.

[PR here](https://github.com/puli/repository/pull/37)

**Comment by webmozart** [comment]
Fixed in puli/repository#37.
